version: '3'

services:
  app:
    build:
      context: .
    image: app-hackathon
    container_name: app-hackathon
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://admin:admin@postgres:5432/DB_HACKATON
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: DB_HACKATON
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
