version: '3'

services:
  app:
    build:
      context: .
    image: app-hackathon
    container_name: app-hackathon
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: DB_HACKATON
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_net

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_net

volumes:
  postgres-data:
  pgadmin_data:

networks:
  db_net:
    driver: bridge
  app_net:
    driver: bridge