version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "hackathon_development"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app_net

  # node_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - db_net

volumes:
  postgres-data:
  pgadmin_data:

networks:
  db_net:
    driver: bridge
  app_net:
    driver: bridge


